echo Installation started!

# TODO: Burası user config side
BASE_DIR="$HOME/SharedObjectBuildingMakefiles"

CPP_LIBRARY_MAKEFILE_PATH="$BASE_DIR/makefiles/01-cpp/01-library"
CPP_COMPILED_LIBRARIES_INC_DIR="$BASE_DIR/CompiledLibraries/01-inc"
CPP_COMPILED_LIBRARIES_SO_DIR="$BASE_DIR/CompiledLibraries/02-so"

CPP_PROJECT_MAKEFILE_PATH="$BASE_DIR/makefiles/01-cpp/02-project"



CPP_LIBRARY_MAKEFILE_PATH_IN_REPO=makefiles/01-cpp/01-library/makefile
mkdir --verbose --parents $CPP_PROJECT_MAKEFILE_PATH
cp --verbose $CPP_LIBRARY_MAKEFILE_PATH_IN_REPO $CPP_LIBRARY_MAKEFILE_PATH
mkdir --verbose --parents $CPP_COMPILED_LIBRARIES_INC_DIR
mkdir --verbose --parents $CPP_COMPILED_LIBRARIES_SO_DIR

CPP_PROJECT_MAKEFILE_PATH_IN_REPO=makefiles/01-cpp/02-project/makefile
mkdir --verbose --parents $CPP_PROJECT_MAKEFILE_PATH
cp --verbose $CPP_PROJECT_MAKEFILE_PATH_IN_REPO $CPP_PROJECT_MAKEFILE_PATH



BASHRC_FILE_PATH="$HOME/.bashrc"
echo -e "\n\n################################################################################" >> $BASHRC_FILE_PATH
echo        "#                    MAKEFILE SPECIFIC CONFIGURATIONS START                    #" >> $BASHRC_FILE_PATH
echo        "################################################################################" >> $BASHRC_FILE_PATH
echo "# NOTE: This part of the file is generated by the Shared Object Building " >> $BASHRC_FILE_PATH
echo "# Makefiles program at " $(date) >> $BASHRC_FILE_PATH
echo -e "\n" >> $BASHRC_FILE_PATH


echo "export CPP_LIBRARY_MAKEFILE_PATH=$CPP_LIBRARY_MAKEFILE_PATH/makefile"  >> $BASHRC_FILE_PATH
echo "export CPP_COMPILED_LIBRARIES_INC_DIR=$CPP_COMPILED_LIBRARIES_INC_DIR" >> $BASHRC_FILE_PATH
echo "export CPP_COMPILED_LIBRARIES_SO_DIR=$CPP_COMPILED_LIBRARIES_SO_DIR"   >> $BASHRC_FILE_PATH
echo "" >> $BASHRC_FILE_PATH

echo "export CPP_PROJECT_MAKEFILE_PATH=$CPP_PROJECT_MAKEFILE_PATH/makefile" >> $BASHRC_FILE_PATH


echo -e "\n" >> $BASHRC_FILE_PATH
echo "################################################################################" >> $BASHRC_FILE_PATH
echo "#                     MAKEFILE SPECIFIC CONFIGURATIONS END                     #" >> $BASHRC_FILE_PATH
echo "################################################################################" >> $BASHRC_FILE_PATH

# Most of the time you don't have to change this path.
# Ld config path is a standard location in Linux distributions.
# The following folder path is used on
# openSUSE 13.2 (Harlequin) (i586)
# and
# Ubuntu 18.04.3 LTS (Bionic Beaver)
# operating systems.
# Check this path for the linux distribution you are using.
LD_CONFIG_DIR=/etc/ld.so.conf.d

echo "# NOTE: Generated by the Shared Object Building Makefiles program at" $(date) | sudo tee $LD_CONFIG_DIR/SharedObjectBuildingMakefiles.conf
echo $CPP_COMPILED_LIBRARIES_SO_DIR | sudo tee --append $LD_CONFIG_DIR/SharedObjectBuildingMakefiles.conf
sudo ldconfig

echo Installation was successful!