echo Installation started!

BASHRC_FILE_PATH="deneme.txt"
echo -e "\n\n################################################################################" >> $BASHRC_FILE_PATH
echo        "#                    MAKEFILE SPECIFIC CONFIGURATIONS START                    #" >> $BASHRC_FILE_PATH
echo        "################################################################################" >> $BASHRC_FILE_PATH
echo "# NOTE: This part of the file is generated by the Shared Object Building " >> $BASHRC_FILE_PATH
echo "# Makefiles program at " $(date) >> $BASHRC_FILE_PATH
echo -e "\n" >> $BASHRC_FILE_PATH


echo "export CPP_LIBRARY_MAKEFILE_PATH=DenemePath" >> $BASHRC_FILE_PATH


echo -e "\n" >> $BASHRC_FILE_PATH
echo "################################################################################" >> $BASHRC_FILE_PATH
echo "#                     MAKEFILE SPECIFIC CONFIGURATIONS END                     #" >> $BASHRC_FILE_PATH
echo "################################################################################" >> $BASHRC_FILE_PATH